spring:
  application:
    name: venta-service

  datasource:
    url: jdbc:postgresql://localhost:5432/venta_db
    username: postgres
    password: Pass123

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  spring:
    cloud:
      openfeign:
        client:
          config:
            default:
              loggerLevel: FULL

server:
  port: 8087

services:
  cliente:
    url: http://localhost:8085
  producto:
    url: http://localhost:8086

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    com.cibertec.venta.api.client: DEBUG
